// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqbbydurphufwxhkseuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxYmJ5ZHVycGh1Znd4aGtzZXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTU1MDEsImV4cCI6MjA1OTI3MTUwMX0.Ttr0YKaHTwkpQ8qkzQFQj6BGDOBUdmU-UWzB2zJn0pA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);